name: create-release

on:
  workflow_dispatch:
  # This event allows manual triggering of the workflow from the GitHub Actions UI.

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Random Version
        id: random-version
        run: echo "::set-output name=version::v$(date +'%Y%m%d%H%M%S')"

      - name: Create GitHub Release
        run: |
          git config --global user.email ${{ secrets.email }}
          git config --global user.name ${{ secrets.userName }}
          # Create a release using the GitHub CLI and the random version
          gh release create ${{ steps.random-version.outputs.version }} --target ${{ github.ref }} --generate-notes -R mike9014/workflow-tests
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
